name: dslideshow_flutter
description: Flutter SlideShow
version: 7.5.0+3
publish_to: none

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^9.0.5
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.0

  qr_flutter: ^4.1.0
  logging: ^1.0.0
  # issue https://github.com/ardera/flutter_packages/issues/43
  video_player: 2.9.5
  duration: ^4.0.3

  xterm: ^4.0.0
  dslideshow_backend: 
    path: ../backend

  dslideshow_common: 
    path: ../common

  system_metrics_widget:
    path: ../system_metrics_widget
  freezed_annotation: ^3.0.0
  
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  flutterpi_gstreamer_video_player: ^0.1.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  meta: ^1.10.0
  freezed: ^3.1.0
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
