name: system_metrics_widget
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.0
  logging: ^1.2.0
  duration: ^4.0.3
  flutter_staggered_grid_view: ^0.7.0
  community_material_icon: ^5.9.55
  font_awesome_flutter: ^10.6.0
  ionicons: ^0.2.2
  feather_icons: ^1.2.0
  google_fonts: ^6.1.0
  #TODO: Fix after NNBD
  # flutter_icons: #^1.1.0 # see more details on https://oblador.github.io/react-native-vector-icons/
  #     git:
  #         url: https://github.com/adarsh-technocrat/flutter-icons.git
  #         ref: null-safety-migration
  dslideshow_backend:
    path: ../backend

  dslideshow_common:
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/google_fonts/
