name: 'dslideshow_common'
version: 2.0.0
description: An absolute bare-bones web app.

environment:
  sdk: '^3.8.0'

dependencies:
  logging: ^1.0.0
  pool: ^1.5.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  json_serializable: ^6.10.0
  freezed: ^3.1.0
  build_runner: ^2.10.4
  test: ^1.15.7
